# install.packages("psych")
library("psych")
df = read.csv("diamonds.csv")
describe(df)

# install.packages("remotes")
library("remotes")
install_github("https://github.com/pablo14/funModeling")
library("funModeling")
df_status(df)
